### ISSUE TITLE
Fixing `filterByDistanceFrom()`

### ISSUE THREAD

**Issue by willdurand** [geocoder-php/GeocodableBehavior#1]
The `filterByDistanceFrom()` method is not perfect:
- Not sure it works fine as a unit test fails;
- Not safe (see: [L216](https://github.com/willdurand/GeocodableBehavior/blob/master/src/GeocodableBehavior.php#L216)). I wonder how to improve this part except to filter values before.

@fzaninotto any ideas to use binding on a column ? Unfortunately, this kind of query cannot be performed in another way.

**Comment by willdurand** [comment]
Fixed by commit f2873e20e33b0bf09a65f6bbd5b6b1e9805fcab0

**Comment by fzaninotto** [comment]
Not safe: you still have an SQL injection risk. I'm working on a fix on the Propel core, please reopen until it's in master.

**Comment by willdurand** [comment]
Oh ok. I thought to pass user values into php functions was enough.
Please, tell me about this SQL issue and the fix you're working on. Thanks.

**Comment by fzaninotto** [comment]
The problem is in [L249](https://github.com/willdurand/GeocodableBehavior/blob/master/src/GeocodableBehavior.php#L249), where you concatenate the distance without any binding.

My fix involves a new type of Criteria comparison, where you can create a condition (in fact, a Criterion) with a statement, a value, and a binding. Something like:

```
$criteria->add('foo = ?', 123, Criteria::RAW, PDO::PARAM_INT);
```

Watch my fork (or a PR) in the upcoming days for more details.

**Comment by willdurand** [comment]
well yes, if I remember some issues I experimented, that's because `Distance` is a virtual column and we cannot bind a virtual column. Your fix should solve that issue as well.

**Comment by willdurand** [comment]
@fzaninotto can you review the `having()` details, not sure about the comparison sign.

**Comment by fzaninotto** [comment]
which commit?

**Comment by willdurand** [comment]
https://github.com/willdurand/GeocodableBehavior/blob/master/src/GeocodableBehavior.php#L226

**Comment by fzaninotto** [comment]
Looks fine by me. And since you have that unit tested, it should be OK. Just mention in your doc that the user needs Propel 1.6.4-dev...

**Comment by willdurand** [comment]
Yep :)
